// Latin and Greek word parts behind anatomical and clinical vocabulary.
//
// The point of Anatomy mode is that "sternocleidomastoid" stops being a
// syllable soup and becomes sternum + clavicle + mastoid process — which is
// also its attachments. That only helps if the glosses are right, so this is
// hand-curated rather than scraped, and the matcher that uses it refuses to
// guess (see anatomyAnnotate.ts).

export type PartKind = "prefix" | "root" | "suffix";

export interface WordPart {
  /** the form as it appears inside a word, without hyphens */
  form: string;
  meaning: string;
  /** L = Latin, Gk = Greek */
  origin: "L" | "Gk";
}

/** Leading elements. Never enough on their own to justify a highlight. */
export const PREFIXES: WordPart[] = [
  { form: "ab", meaning: "away from", origin: "L" },
  { form: "ad", meaning: "toward", origin: "L" },
  { form: "ante", meaning: "before, in front of", origin: "L" },
  { form: "anti", meaning: "against", origin: "Gk" },
  { form: "bi", meaning: "two", origin: "L" },
  { form: "circum", meaning: "around", origin: "L" },
  { form: "contra", meaning: "against, opposite", origin: "L" },
  { form: "dia", meaning: "through, across", origin: "Gk" },
  { form: "ecto", meaning: "outside, outer", origin: "Gk" },
  { form: "endo", meaning: "within, inner", origin: "Gk" },
  { form: "epi", meaning: "upon, over", origin: "Gk" },
  { form: "extra", meaning: "outside of", origin: "L" },
  { form: "hemi", meaning: "half", origin: "Gk" },
  { form: "hyper", meaning: "above, excessive", origin: "Gk" },
  { form: "hypo", meaning: "below, deficient", origin: "Gk" },
  { form: "infra", meaning: "below, beneath", origin: "L" },
  { form: "inter", meaning: "between", origin: "L" },
  { form: "intra", meaning: "within", origin: "L" },
  { form: "iso", meaning: "equal", origin: "Gk" },
  { form: "juxta", meaning: "next to", origin: "L" },
  { form: "meso", meaning: "middle", origin: "Gk" },
  { form: "meta", meaning: "beyond, change", origin: "Gk" },
  { form: "para", meaning: "beside, near", origin: "Gk" },
  { form: "peri", meaning: "around", origin: "Gk" },
  { form: "poly", meaning: "many", origin: "Gk" },
  { form: "post", meaning: "after, behind", origin: "L" },
  { form: "retro", meaning: "backward, behind", origin: "L" },
  { form: "sub", meaning: "under, below", origin: "L" },
  { form: "supra", meaning: "above", origin: "L" },
  { form: "trans", meaning: "across, through", origin: "L" },
];

/**
 * Roots. A highlight always needs at least one of these — a word built only
 * from a prefix and a suffix is almost always ordinary English.
 */
export const ROOTS: WordPart[] = [
  // --- structures ---
  { form: "aden", meaning: "gland", origin: "Gk" },
  { form: "adip", meaning: "fat", origin: "L" },
  { form: "angi", meaning: "vessel", origin: "Gk" },
  { form: "arthr", meaning: "joint", origin: "Gk" },
  { form: "blephar", meaning: "eyelid", origin: "Gk" },
  { form: "brachi", meaning: "arm", origin: "L" },
  { form: "bronch", meaning: "airway", origin: "Gk" },
  { form: "bucc", meaning: "cheek", origin: "L" },
  { form: "calcane", meaning: "heel bone", origin: "L" },
  { form: "capit", meaning: "head", origin: "L" },
  { form: "cardi", meaning: "heart", origin: "Gk" },
  { form: "carp", meaning: "wrist", origin: "Gk" },
  { form: "cephal", meaning: "head", origin: "Gk" },
  { form: "cerebr", meaning: "brain", origin: "L" },
  { form: "cervic", meaning: "neck", origin: "L" },
  { form: "cheil", meaning: "lip", origin: "Gk" },
  { form: "chondr", meaning: "cartilage", origin: "Gk" },
  { form: "cleid", meaning: "clavicle", origin: "Gk" },
  { form: "coccyg", meaning: "coccyx, tailbone", origin: "Gk" },
  { form: "cochle", meaning: "cochlea, snail shell", origin: "Gk" },
  { form: "col", meaning: "colon", origin: "Gk" },
  { form: "cost", meaning: "rib", origin: "L" },
  { form: "crani", meaning: "skull", origin: "Gk" },
  { form: "cutane", meaning: "skin", origin: "L" },
  { form: "cyst", meaning: "bladder, sac", origin: "Gk" },
  { form: "cyt", meaning: "cell", origin: "Gk" },
  { form: "dactyl", meaning: "finger or toe", origin: "Gk" },
  { form: "dent", meaning: "tooth", origin: "L" },
  { form: "dermat", meaning: "skin", origin: "Gk" },
  { form: "derm", meaning: "skin", origin: "Gk" },
  { form: "duoden", meaning: "duodenum", origin: "L" },
  { form: "encephal", meaning: "brain", origin: "Gk" },
  { form: "enter", meaning: "intestine", origin: "Gk" },
  { form: "gastr", meaning: "stomach", origin: "Gk" },
  { form: "gingiv", meaning: "gum", origin: "L" },
  { form: "gloss", meaning: "tongue", origin: "Gk" },
  { form: "gnath", meaning: "jaw", origin: "Gk" },
  { form: "hepat", meaning: "liver", origin: "Gk" },
  { form: "hemat", meaning: "blood", origin: "Gk" },
  { form: "hist", meaning: "tissue", origin: "Gk" },
  { form: "humer", meaning: "humerus, upper arm", origin: "L" },
  { form: "hyster", meaning: "uterus", origin: "Gk" },
  { form: "ile", meaning: "ileum", origin: "L" },
  { form: "ili", meaning: "ilium, hip bone", origin: "L" },
  { form: "kerat", meaning: "cornea, horny tissue", origin: "Gk" },
  { form: "labi", meaning: "lip", origin: "L" },
  { form: "lacrim", meaning: "tear", origin: "L" },
  { form: "laryng", meaning: "larynx, voice box", origin: "Gk" },
  { form: "lingu", meaning: "tongue", origin: "L" },
  { form: "lumb", meaning: "lower back, loin", origin: "L" },
  { form: "mamm", meaning: "breast", origin: "L" },
  { form: "mast", meaning: "breast", origin: "Gk" },
  { form: "mastoid", meaning: "mastoid process", origin: "Gk" },
  { form: "maxill", meaning: "upper jaw", origin: "L" },
  { form: "medull", meaning: "marrow, inner part", origin: "L" },
  { form: "mening", meaning: "membrane around the brain", origin: "Gk" },
  { form: "metr", meaning: "uterus", origin: "Gk" },
  { form: "myel", meaning: "marrow, spinal cord", origin: "Gk" },
  { form: "myo", meaning: "muscle", origin: "Gk" },
  { form: "nas", meaning: "nose", origin: "L" },
  { form: "nephr", meaning: "kidney", origin: "Gk" },
  { form: "neur", meaning: "nerve", origin: "Gk" },
  { form: "ocul", meaning: "eye", origin: "L" },
  { form: "odont", meaning: "tooth", origin: "Gk" },
  { form: "onych", meaning: "nail", origin: "Gk" },
  { form: "oophor", meaning: "ovary", origin: "Gk" },
  { form: "ophthalm", meaning: "eye", origin: "Gk" },
  { form: "orchi", meaning: "testis", origin: "Gk" },
  { form: "oste", meaning: "bone", origin: "Gk" },
  { form: "ovari", meaning: "ovary", origin: "L" },
  { form: "palat", meaning: "palate", origin: "L" },
  { form: "pancreat", meaning: "pancreas", origin: "Gk" },
  { form: "pariet", meaning: "wall", origin: "L" },
  { form: "patell", meaning: "kneecap", origin: "L" },
  { form: "pector", meaning: "chest", origin: "L" },
  { form: "pelv", meaning: "pelvis", origin: "L" },
  { form: "phalang", meaning: "finger or toe bone", origin: "Gk" },
  { form: "pharyng", meaning: "pharynx, throat", origin: "Gk" },
  { form: "phleb", meaning: "vein", origin: "Gk" },
  { form: "phren", meaning: "diaphragm", origin: "Gk" },
  { form: "pleur", meaning: "pleura, side", origin: "Gk" },
  { form: "pneumon", meaning: "lung", origin: "Gk" },
  { form: "pod", meaning: "foot", origin: "Gk" },
  { form: "poplite", meaning: "back of the knee", origin: "L" },
  { form: "proct", meaning: "rectum, anus", origin: "Gk" },
  { form: "pulmon", meaning: "lung", origin: "L" },
  { form: "pyel", meaning: "renal pelvis", origin: "Gk" },
  { form: "ren", meaning: "kidney", origin: "L" },
  { form: "rhin", meaning: "nose", origin: "Gk" },
  { form: "sacr", meaning: "sacrum", origin: "L" },
  { form: "salping", meaning: "tube, uterine tube", origin: "Gk" },
  { form: "sarc", meaning: "flesh", origin: "Gk" },
  { form: "scapul", meaning: "shoulder blade", origin: "L" },
  { form: "sept", meaning: "partition", origin: "L" },
  { form: "sial", meaning: "saliva", origin: "Gk" },
  { form: "somat", meaning: "body", origin: "Gk" },
  { form: "splen", meaning: "spleen", origin: "Gk" },
  { form: "spondyl", meaning: "vertebra", origin: "Gk" },
  { form: "stern", meaning: "sternum, breastbone", origin: "Gk" },
  { form: "stomat", meaning: "mouth", origin: "Gk" },
  { form: "tars", meaning: "ankle", origin: "Gk" },
  { form: "ten", meaning: "tendon", origin: "Gk" },
  { form: "thorac", meaning: "chest", origin: "Gk" },
  { form: "thromb", meaning: "clot", origin: "Gk" },
  { form: "thyr", meaning: "shield (the thyroid cartilage)", origin: "Gk" },
  { form: "tibi", meaning: "tibia, shin bone", origin: "L" },
  { form: "trache", meaning: "trachea, windpipe", origin: "Gk" },
  { form: "trich", meaning: "hair", origin: "Gk" },
  { form: "umbilic", meaning: "navel", origin: "L" },
  { form: "ureter", meaning: "ureter", origin: "Gk" },
  { form: "urethr", meaning: "urethra", origin: "Gk" },
  { form: "uter", meaning: "uterus", origin: "L" },
  { form: "vascul", meaning: "vessel", origin: "L" },
  { form: "ven", meaning: "vein", origin: "L" },
  { form: "ventricul", meaning: "ventricle, small cavity", origin: "L" },
  { form: "vertebr", meaning: "vertebra", origin: "L" },
  { form: "vesic", meaning: "bladder", origin: "L" },
  { form: "viscer", meaning: "internal organ", origin: "L" },

  // --- qualities and processes ---
  { form: "alb", meaning: "white", origin: "L" },
  { form: "brady", meaning: "slow", origin: "Gk" },
  { form: "cyan", meaning: "blue", origin: "Gk" },
  { form: "erythr", meaning: "red", origin: "Gk" },
  { form: "glyc", meaning: "sugar", origin: "Gk" },
  { form: "leuk", meaning: "white", origin: "Gk" },
  { form: "lip", meaning: "fat", origin: "Gk" },
  { form: "lith", meaning: "stone", origin: "Gk" },
  { form: "macro", meaning: "large", origin: "Gk" },
  { form: "melan", meaning: "black, dark", origin: "Gk" },
  { form: "micro", meaning: "small", origin: "Gk" },
  { form: "morph", meaning: "form, shape", origin: "Gk" },
  { form: "necr", meaning: "death", origin: "Gk" },
  { form: "olig", meaning: "few, scanty", origin: "Gk" },
  { form: "path", meaning: "disease", origin: "Gk" },
  { form: "phag", meaning: "eat, swallow", origin: "Gk" },
  { form: "pseud", meaning: "false", origin: "Gk" },
  { form: "scler", meaning: "hard", origin: "Gk" },
  { form: "sten", meaning: "narrow", origin: "Gk" },
  { form: "tachy", meaning: "fast", origin: "Gk" },
  { form: "therm", meaning: "heat", origin: "Gk" },
  { form: "troph", meaning: "nourishment, growth", origin: "Gk" },
  { form: "xanth", meaning: "yellow", origin: "Gk" },
];

/** Trailing elements. */
export const SUFFIXES: WordPart[] = [
  { form: "algia", meaning: "pain", origin: "Gk" },
  { form: "blast", meaning: "immature cell", origin: "Gk" },
  { form: "cele", meaning: "hernia, swelling", origin: "Gk" },
  { form: "centesis", meaning: "surgical puncture", origin: "Gk" },
  { form: "clast", meaning: "cell that breaks down", origin: "Gk" },
  { form: "cyte", meaning: "cell", origin: "Gk" },
  { form: "desis", meaning: "surgical fusion", origin: "Gk" },
  { form: "ectomy", meaning: "surgical removal", origin: "Gk" },
  { form: "emia", meaning: "blood condition", origin: "Gk" },
  { form: "genesis", meaning: "formation, origin", origin: "Gk" },
  { form: "genic", meaning: "producing", origin: "Gk" },
  { form: "gram", meaning: "record, image", origin: "Gk" },
  { form: "graphy", meaning: "process of recording", origin: "Gk" },
  { form: "itis", meaning: "inflammation", origin: "Gk" },
  { form: "logy", meaning: "study of", origin: "Gk" },
  { form: "lysis", meaning: "breakdown, loosening", origin: "Gk" },
  { form: "malacia", meaning: "softening", origin: "Gk" },
  { form: "megaly", meaning: "enlargement", origin: "Gk" },
  { form: "oid", meaning: "resembling", origin: "Gk" },
  { form: "oma", meaning: "tumour, mass", origin: "Gk" },
  { form: "osis", meaning: "abnormal condition", origin: "Gk" },
  { form: "ostomy", meaning: "surgical opening", origin: "Gk" },
  { form: "otomy", meaning: "surgical incision", origin: "Gk" },
  { form: "pathy", meaning: "disease", origin: "Gk" },
  { form: "penia", meaning: "deficiency", origin: "Gk" },
  { form: "pexy", meaning: "surgical fixation", origin: "Gk" },
  { form: "phasia", meaning: "speech", origin: "Gk" },
  { form: "plasia", meaning: "formation, growth", origin: "Gk" },
  { form: "plasty", meaning: "surgical repair", origin: "Gk" },
  { form: "plegia", meaning: "paralysis", origin: "Gk" },
  { form: "pnea", meaning: "breathing", origin: "Gk" },
  { form: "ptosis", meaning: "drooping", origin: "Gk" },
  { form: "rrhagia", meaning: "bursting forth, heavy flow", origin: "Gk" },
  { form: "rrhaphy", meaning: "surgical suturing", origin: "Gk" },
  { form: "rrhea", meaning: "flow, discharge", origin: "Gk" },
  { form: "rrhexis", meaning: "rupture", origin: "Gk" },
  { form: "sclerosis", meaning: "hardening", origin: "Gk" },
  { form: "scopy", meaning: "visual examination", origin: "Gk" },
  { form: "scope", meaning: "instrument for viewing", origin: "Gk" },
  { form: "spasm", meaning: "involuntary contraction", origin: "Gk" },
  { form: "stasis", meaning: "stopping, controlling", origin: "Gk" },
  { form: "stenosis", meaning: "narrowing", origin: "Gk" },
  { form: "tomy", meaning: "incision", origin: "Gk" },
  { form: "trophy", meaning: "growth, nourishment", origin: "Gk" },
];

/**
 * Whole words worth glossing on sight: Latin muscle and direction terms that
 * don't decompose usefully, and irregular clinical terms. Keys are lowercase.
 */
export const WHOLE_TERMS: Record<string, string> = {
  // direction and position
  anterior: "L. in front of",
  posterior: "L. behind",
  superior: "L. above",
  inferior: "L. below",
  medialis: "L. toward the midline",
  medial: "L. toward the midline",
  lateralis: "L. toward the side",
  lateral: "L. toward the side",
  proximal: "L. nearer the trunk",
  distal: "L. further from the trunk",
  superficialis: "L. near the surface",
  profundus: "L. deep",
  dorsi: "L. of the back",
  dorsal: "L. of the back",
  ventral: "L. of the belly, front",
  palmar: "L. of the palm",
  plantar: "L. of the sole of the foot",
  supine: "L. lying face up",

  // muscle shape and size
  rectus: "L. straight",
  obliquus: "L. slanting",
  oblique: "L. slanting",
  transversus: "L. lying across",
  longus: "L. long",
  brevis: "L. short",
  magnus: "L. great, large",
  maximus: "L. largest",
  minimus: "L. smallest",
  latissimus: "L. widest",
  gracilis: "L. slender",
  teres: "L. round, cylindrical",
  serratus: "L. saw-toothed",
  vastus: "L. vast, huge",
  biceps: "L. two-headed",
  triceps: "L. three-headed",
  quadriceps: "L. four-headed",
  digastric: "L. two-bellied",
  soleus: "L. sole-shaped, like a flatfish",
  sartorius: "L. tailor's muscle — it crosses the legs",
  piriformis: "L. pear-shaped",
  rhomboid: "Gk. rhombus-shaped",
  trapezius: "Gk. trapezium-shaped",
  deltoid: "Gk. shaped like the letter delta",
  platysma: "Gk. flat plate",
  masseter: "Gk. chewer",
  buccinator: "L. trumpeter — it puffs the cheek",
  orbicularis: "L. little circle",

  // action
  flexor: "L. bender — decreases the joint angle",
  extensor: "L. straightener — increases the joint angle",
  abductor: "L. draws away from the midline",
  adductor: "L. draws toward the midline",
  levator: "L. lifter",
  depressor: "L. one that presses down",
  supinator: "L. turns the palm upward",
  pronator: "L. turns the palm downward",
  tensor: "L. one that stretches",
  constrictor: "L. one that draws together",
  sphincter: "Gk. that which binds tight",

  // "of the …" — the genitives that name a muscle's target
  pollicis: "L. of the thumb",
  hallucis: "L. of the great toe",
  digitorum: "L. of the fingers or toes",
  indicis: "L. of the index finger",
  minimi: "L. of the smallest (little finger or toe)",
  femoris: "L. of the thigh",
  oris: "L. of the mouth",
  oculi: "L. of the eye",
  abdominis: "L. of the abdomen",
  capitis: "L. of the head",
  cervicis: "L. of the neck",
  thoracis: "L. of the thorax",
  lumborum: "L. of the loins",
  carpi: "L. of the wrist",
  radialis: "L. of the radius, thumb side",
  ulnaris: "L. of the ulna, little-finger side",
  tibialis: "L. of the tibia, shin",
  fibularis: "L. of the fibula, outer leg",
  peroneus: "Gk. of the fibula, outer leg",
  scapulae: "L. of the shoulder blade",
  humeri: "L. of the humerus",
  uteri: "L. of the uterus",

  // structures whose names are the Latin word
  fascia: "L. band or bandage",
  aponeurosis: "Gk. sheet-like tendon",
  ligament: "L. that which binds",
  tendon: "L. that which stretches",
  foramen: "L. opening, hole",
  fossa: "L. ditch, shallow depression",
  sulcus: "L. groove, furrow",
  gyrus: "Gk. ring, circle — a brain ridge",
  hilum: "L. little thing — where vessels enter an organ",
  meatus: "L. passage",
  ostium: "L. door, opening",
  lumen: "L. light — the space inside a tube",
  septum: "L. partition",
  raphe: "Gk. seam",
  ala: "L. wing",
  cornu: "L. horn",
  crus: "L. leg, leg-like part",
  ansa: "L. loop, handle",
  falx: "L. sickle",
  tentorium: "L. tent",
  vermis: "L. worm",
  cauda: "L. tail",
  caput: "L. head",
  corpus: "L. body",
  cortex: "L. bark, outer layer",
  medulla: "L. marrow, inner part",
  plexus: "L. braid, network",
  rete: "L. net",
  vas: "L. vessel",
  vasa: "L. vessels",
  bursa: "L. purse",
  villi: "L. shaggy hairs",
  villus: "L. shaggy hair",
  alveolus: "L. small hollow",
  alveoli: "L. small hollows",
  glomerulus: "L. little ball of yarn",
  papilla: "L. nipple, small projection",
  fovea: "L. small pit",
  labrum: "L. lip, rim",
  lamina: "L. thin plate",
  pedicle: "L. little foot",
  tubercle: "L. small swelling",
  tuberosity: "L. broad rough swelling",
  trochanter: "Gk. runner — a hip prominence",
  condyle: "Gk. knuckle",
  epicondyle: "Gk. upon the knuckle",
  malleolus: "L. little hammer — the ankle knob",
  olecranon: "Gk. point of the elbow",
  acromion: "Gk. tip of the shoulder",
  coracoid: "Gk. like a crow's beak",
  styloid: "Gk. like a pillar or pen",
  xiphoid: "Gk. sword-shaped",
  hyoid: "Gk. shaped like the letter upsilon",
  sagittal: "L. arrow-like — front-to-back plane",
  coronal: "L. crown-like — side-to-side plane",
  incisura: "L. notch",
  sinus: "L. hollow, cavity",
  antrum: "L. cave",
  atrium: "L. entrance hall",
  ventricle: "L. small belly",
  auricle: "L. little ear",
  valve: "L. leaf of a folding door",
  chorda: "Gk. cord, string",
  tunica: "L. coat, covering",
  pia: "L. tender",
  dura: "L. tough",
  arachnoid: "Gk. spider-like, cobwebby",
};

/**
 * Words the matcher must never touch. Ordinary English that happens to
 * decompose — highlighting these is exactly the noise that makes a feature
 * like this annoying rather than useful.
 */
export const STOPWORDS = new Set([
  // Caught by the audit against real decks: these decompose convincingly and
  // are completely wrong. "intervene" is from venire, to come — not vein;
  // a histogram is a bar chart, not tissue; phrenology read skull bumps.
  "intervene", "intervention", "intervenes", "intervening", "histogram",
  "histograms", "phrenology", "phrenologist", "adenine", "adenosine",
  "isotherm", "isothermal", "process", "processes", "processing", "major",
  "majority", "minor", "minority", "prone", "proneness",
  "capital", "capitalize", "central", "centre", "center", "material", "maternal",
  "personal", "national", "general", "several", "mineral", "literal", "liberal",
  "natural", "cultural", "digital", "logical", "topical", "typical", "critical",
  "medical", "surgical", "clinical", "physical", "chemical", "vertical",
  "horizontal", "normal", "abnormal", "formal", "informal", "minimal", "maximal",
  "optimal", "terminal", "internal", "external", "eternal", "journal", "signal",
  "spinal", "final", "renal", "penal", "canal", "banal", "total", "vital",
  "dental", "mental", "rental", "parental", "potential", "essential",
  "sequential", "residential", "presidential", "confidential", "influential",
  "colon", "colonel", "colony", "column", "common", "compose", "compound",
  "content", "context", "continue", "contrast", "control", "convert",
  "interest", "interior", "internet", "interval", "interview", "introduce",
  "postal", "poster", "posture", "position", "positive", "possible",
  "process", "produce", "product", "program", "project", "promise", "protect",
  "protein", "provide", "public", "publish", "purpose", "subject", "submit",
  "subset", "substance", "subtract", "suburb", "success", "sudden", "suffer",
  "suggest", "summary", "support", "suppose", "surface", "surprise", "survey",
  "survive", "system", "transfer", "transit", "translate", "transport",
  "adapt", "addition", "address", "adequate", "adjust", "admit", "adopt",
  "advance", "advantage", "adverse", "advice", "advise", "bicycle", "bilingual",
  "billion", "binary", "biology", "biopsy", "diagram", "dialogue", "diamond",
  "diary", "dietary", "different", "difficult", "digest", "dinner", "direct",
  "discuss", "disease", "display", "distance", "district", "isolate", "issue",
  "metal", "method", "metric", "parallel", "parameter", "parent", "particle",
  "partial", "particular", "passage", "patient", "pattern", "percent",
  "perfect", "perform", "perhaps", "period", "permit", "person", "persist",
  "polish", "policy", "polite", "political", "pollution", "popular",
  "population", "portion", "possess", "potential", "practice", "precise",
  "predict", "prefer", "premise", "prepare", "present", "preserve", "pressure",
  "pretend", "prevent", "previous", "primary", "principal", "principle",
  "print", "prior", "private", "problem", "procedure", "proceed",
  "retail", "retain", "return", "reveal", "review", "revise", "isolated",
  "tension", "tendency", "tender", "tenure", "tennis", "tentative",
  "lipstick", "listen", "little", "living", "location", "logic", "longer",
  "longest", "master", "masterpiece", "mastery", "matter", "measure",
  "mechanism", "median", "medium", "meeting", "member", "memory", "mention",
  "message", "middle", "military", "million", "minister", "minute", "mission",
  "mistake", "mixture", "modern", "moment", "monitor", "monthly", "morning",
  "mortgage", "mother", "motion", "mountain", "movement", "multiple", "muscle",
  "musical", "mystery", "renew", "rental", "repair", "repeat", "replace",
  "report", "represent", "request", "require", "research", "reserve",
  "resident", "resist", "resolve", "resource", "respect", "respond",
  "response", "restore", "result", "retire", "reveal", "science", "scientist",
  "section", "sector", "secure", "seldom", "select", "senate", "senior",
  "sense", "sentence", "separate", "series", "serious", "servant", "serve",
  "service", "session", "setting", "settle", "seven", "several", "severe",
  "shadow", "shallow", "signal", "silence", "similar", "simple", "single",
  "sister", "situation", "society", "soldier", "solution", "somebody",
  "someone", "something", "sometimes", "somewhat", "sorry", "sound", "source",
  "southern", "special", "species", "specific", "spirit", "sponsor", "sport",
  "spread", "spring", "square", "stable", "staff", "stage", "stand",
  "standard", "start", "state", "statement", "station", "statistic", "status",
  "steady", "steel", "stick", "still", "stock", "stomach", "stone", "storage",
  "store", "storm", "story", "straight", "strange", "strategy", "stream",
  "street", "strength", "stress", "stretch", "strike", "string", "strong",
  "structure", "struggle", "student", "studio", "study", "stuff", "stupid",
  "style", "subject", "succeed", "sugar", "suit", "summer", "sunday", "super",
  "supply", "suppose", "sure", "surgery", "surround", "survey", "suspect",
  "sustain", "swear", "sweet", "swing", "switch", "symbol", "symptom",
]);
