// A lookup table of medical roots, prefixes and suffixes.
//
// Deliberately separate from the highlighting data in anatomyTerms.ts. That
// set is small and heavily audited, because anything in it marks up your
// cards automatically and a wrong gloss there poisons the whole feature. This
// one is only ever consulted when you type into the search box, so breadth
// costs nothing and short or ambiguous forms ("os", "my-") are welcome.

export interface ReferenceEntry {
  /** the combining form, as it is conventionally written */
  form: string;
  meaning: string;
  origin: "L" | "Gk" | "L/Gk";
  /** a word that shows it working */
  example?: string;
}

type Row = [string, string, ReferenceEntry["origin"], string?];

const ROWS: Row[] = [
  // A
  ["a-, an-", "not, without", "Gk", "analgesic, anencephaly"],
  ["ab-", "away from", "L", "abduction"],
  ["abdomin-", "abdomen", "L", "abdominoplasty"],
  ["-ac", "pertaining to", "Gk", "cardiac, celiac"],
  ["acanth-", "thorn, spine", "Gk", "acanthocyte"],
  ["acou-, -acusis", "hearing", "Gk", "hyperacusis"],
  ["acr-", "extremity, topmost", "Gk", "acromegaly, acromion"],
  ["-ad", "toward", "L", "dorsad, ventrad"],
  ["ad-", "toward, increase", "L", "adduction"],
  ["aden-", "gland", "Gk", "adenocarcinoma"],
  ["adip-", "fat", "L", "adipocyte"],
  ["adren-", "adrenal gland (ad- + ren, kidney)", "L", "adrenaline"],
  ["aer(o)-", "air, gas", "Gk", "aerophagia"],
  ["-al", "pertaining to", "L", "abdominal, femoral"],
  ["alb-", "white", "L", "albino, tunica albuginea"],
  ["alge-, -algia", "pain", "Gk", "analgesic, myalgia"],
  ["all-", "other, different", "Gk", "allograft"],
  ["ambi-", "both sides", "L", "ambidextrous"],
  ["amnio-", "amnion, fetal sac", "Gk", "amniocentesis"],
  ["amph(i)-", "on both sides", "Gk", "amphiarthrosis"],
  ["amyl(o)-", "starch", "L", "amylase"],
  ["ana-", "up, back, again", "Gk", "anaplasia"],
  ["andr-", "man, male", "Gk", "androgen"],
  ["angi-", "vessel", "Gk", "angiogram, angioplasty"],
  ["aniso-", "unequal", "Gk", "anisocytosis"],
  ["ankyl-", "crooked, bent, stiff", "Gk", "ankylosis"],
  ["ante-", "before, in front of", "L", "antepartum"],
  ["anti-", "against", "Gk", "antibody"],
  ["apo-", "away from, separated", "Gk", "apoptosis, apocrine"],
  ["arteri(o)-", "artery", "Gk", "arteriole"],
  ["arthr-", "joint", "Gk", "arthritis, arthroscopy"],
  ["articul-", "joint", "L", "articulation"],
  ["-ary", "pertaining to", "L", "coronary, biliary"],
  ["-ase", "enzyme", "Gk", "lactase, amylase"],
  ["-asthenia", "weakness", "Gk", "myasthenia gravis"],
  ["atel(o)-", "incomplete", "Gk", "atelectasis"],
  ["ather-", "fatty, gruel-like deposit", "Gk", "atherosclerosis"],
  ["atri-", "atrium, entrance hall", "L", "atrioventricular"],
  ["aur-", "ear", "L", "aural, auricle"],
  ["aut-", "self", "Gk", "autoimmune, autophagy"],
  ["axill-", "armpit", "L", "axillary"],

  // B
  ["bacteri-", "bacteria", "Gk", "bacteriophage"],
  ["balan-", "glans", "Gk", "balanitis"],
  ["bas-", "base, foundation", "Gk", "basolateral"],
  ["bi-", "two, twice", "L", "biceps, bilateral"],
  ["bio-", "life", "Gk", "biology, biopsy"],
  ["blast-", "germ, bud, immature cell", "Gk", "osteoblast"],
  ["blephar(o)-", "eyelid", "Gk", "blepharoplasty"],
  ["brachi(o)-", "arm", "L", "brachial artery"],
  ["brachy-", "short", "Gk", "brachycephalic"],
  ["brady-", "slow", "Gk", "bradycardia"],
  ["bronch(i)-", "bronchus, airway", "Gk", "bronchitis"],
  ["bucc(o)-", "cheek", "L", "buccal"],
  ["burs(o)-", "bursa, purse", "L", "bursitis"],

  // C
  ["capill-", "hair", "L", "capillary"],
  ["capit-", "head", "L", "capitate, decapitation"],
  ["carcin-", "cancer, crab", "Gk", "carcinoma"],
  ["cardi-", "heart", "Gk", "cardiology, tachycardia"],
  ["carp-", "wrist", "Gk", "carpal, metacarpal"],
  ["cata-", "down, under", "Gk", "catabolism"],
  ["-cele", "hernia, swelling", "Gk", "hydrocele, varicocele"],
  ["-centesis", "surgical puncture", "Gk", "thoracentesis"],
  ["cephal(o)-", "head", "Gk", "hydrocephalus"],
  ["cerebell(o)-", "cerebellum, little brain", "L", "cerebellar"],
  ["cerebr(o)-", "brain", "L", "cerebral cortex"],
  ["cervic-", "neck, cervix", "L", "cervical vertebrae"],
  ["cheil-, chil-", "lip", "Gk", "cheilitis"],
  ["chir-, cheir-", "hand", "Gk", "chiropractor"],
  ["chlor-", "green", "Gk", "chlorophyll"],
  ["chol(e)-", "bile", "Gk", "cholecystitis"],
  ["cholecyst(o)-", "gallbladder", "Gk", "cholecystectomy"],
  ["chondr(o)-", "cartilage", "Gk", "chondrocyte"],
  ["chrom(ato)-", "colour", "Gk", "haemochromatosis"],
  ["-cidal, -cide", "killing", "L", "bactericidal"],
  ["cili-", "eyelash, cilium", "L", "ciliary body"],
  ["circum-", "around", "L", "circumcision, circumflex"],
  ["-clast", "break down", "Gk", "osteoclast"],
  ["co-, com-, con-", "with, together", "L", "coenzyme"],
  ["-coccus", "round, berry-shaped", "Gk", "streptococcus"],
  ["col-, colo-", "colon", "Gk", "colonoscopy"],
  ["colp-", "vagina", "Gk", "colposcopy"],
  ["contra-", "against, opposite", "L", "contralateral"],
  ["cor-, core-", "pupil of the eye", "Gk", "corectopia"],
  ["cord-, cardi-", "heart", "L", "commotio cordis"],
  ["cornu-", "horn", "L", "greater cornu"],
  ["coron-", "crown", "L", "coronary, coronal"],
  ["cortic-", "cortex, bark, outer layer", "L", "corticosteroid"],
  ["cost-", "rib", "L", "intercostal, costochondral"],
  ["cox-", "hip", "L", "coxa vara"],
  ["crani(o)-", "skull", "Gk", "craniotomy"],
  ["-crine, crin(o)-", "to secrete", "Gk", "endocrine, exocrine"],
  ["cry(o)-", "cold", "Gk", "cryotherapy"],
  ["cutane-, cut-", "skin", "L", "subcutaneous"],
  ["cyan(o)-", "blue", "Gk", "cyanosis"],
  ["cyst(o)-", "bladder, sac", "Gk", "cystoscopy"],
  ["cyt(o)-, -cyte", "cell", "Gk", "cytoplasm, leukocyte"],

  // D
  ["dacry(o)-", "tear", "Gk", "dacryocystitis"],
  ["dactyl(o)-", "finger, toe", "Gk", "polydactyly"],
  ["de-", "down, away from", "L", "dehydration"],
  ["dent-", "tooth", "L", "dentition, dental"],
  ["derm(at)(o)-", "skin", "Gk", "dermatology, epidermis"],
  ["-desis", "surgical binding, fusion", "Gk", "arthrodesis"],
  ["dextr(o)-", "right", "L", "dextrocardia"],
  ["di-", "two", "Gk", "diplopia"],
  ["dia-", "through, across", "Gk", "dialysis, diaphragm"],
  ["digit-", "finger, toe", "L", "digitorum"],
  ["diplo-", "double", "Gk", "diploid"],
  ["-dipsia", "thirst", "Gk", "polydipsia"],
  ["dors(o)-", "back", "L", "dorsal, latissimus dorsi"],
  ["duoden-", "duodenum (twelve fingers' breadth)", "L", "duodenal ulcer"],
  ["dur-", "hard, tough", "L", "dura mater"],
  ["dynam(o)-", "force, power", "Gk", "dynamometer"],
  ["-dynia", "pain", "Gk", "vulvodynia"],
  ["dys-", "bad, difficult, abnormal", "Gk", "dysphagia, dysplasia"],

  // E
  ["ec-", "out, away", "Gk", "ectopic"],
  ["ect(o)-", "outer, outside", "Gk", "ectoderm"],
  ["-ectasis", "dilation, expansion", "Gk", "bronchiectasis"],
  ["-ectomy", "surgical removal", "Gk", "appendectomy"],
  ["-emia, -aemia", "blood condition", "Gk", "anaemia, hyperglycaemia"],
  ["-emesis", "vomiting", "Gk", "haematemesis"],
  ["encephal(o)-", "brain", "Gk", "encephalitis"],
  ["endo-", "within, inner", "Gk", "endometrium, endoscopy"],
  ["enter(o)-", "intestine", "Gk", "gastroenterology"],
  ["eosin(o)-", "red (dawn-coloured)", "Gk", "eosinophil"],
  ["epi-", "upon, over", "Gk", "epidermis, epicardium"],
  ["episi(o)-", "vulva, pubic region", "Gk", "episiotomy"],
  ["erythr(o)-", "red", "Gk", "erythrocyte"],
  ["eu-", "good, well, normal", "Gk", "euthyroid"],
  ["ex-, exo-", "out, outside", "L/Gk", "exophthalmos"],
  ["extra-", "outside of", "L", "extracellular"],

  // F
  ["faci-", "face", "L", "facial nerve"],
  ["fibr-", "fibre", "L", "fibroblast, fibrosis"],
  ["fil-", "thread", "L", "filum terminale"],
  ["foramin-", "opening, hole", "L", "foraminotomy"],
  ["-form", "having the shape of", "L", "cuneiform, falciform"],
  ["front-", "forehead", "L", "frontal lobe"],

  // G
  ["galact-", "milk", "Gk", "galactorrhoea"],
  ["gastr(o)-", "stomach", "Gk", "gastritis, gastrocnemius"],
  ["-gen, -genic", "producing, born of", "Gk", "pathogenic, carcinogen"],
  ["-genesis", "formation, origin", "Gk", "neurogenesis"],
  ["genu-", "knee", "L", "genu valgum"],
  ["-geusia", "taste", "Gk", "dysgeusia"],
  ["gingiv-", "gum", "L", "gingivitis"],
  ["glauc(o)-", "grey, bluish-grey", "Gk", "glaucoma"],
  ["gloss(o)-, glott-", "tongue", "Gk", "hypoglossal, glossitis"],
  ["gluc(o)-, glyc(o)-", "sugar, sweet", "Gk", "glucose, glycolysis"],
  ["gnath-", "jaw", "Gk", "prognathism"],
  ["-gnosis", "knowledge", "Gk", "diagnosis, prognosis"],
  ["gon-", "seed, reproductive", "Gk", "gonad"],
  ["-gram", "record, image", "Gk", "angiogram"],
  ["-graphy", "process of recording", "Gk", "mammography"],
  ["gyn(aec)(o)-", "woman", "Gk", "gynaecology"],

  // H
  ["haem(at)-, hem(at)-", "blood", "Gk", "haematoma, haemostasis"],
  ["hemi-", "half", "Gk", "hemiplegia, hemisphere"],
  ["hepat(o)-", "liver", "Gk", "hepatitis"],
  ["heter(o)-", "other, different", "Gk", "heterogeneous"],
  ["hidr(o)-", "sweat", "Gk", "hyperhidrosis"],
  ["hist(o)-", "tissue", "Gk", "histology"],
  ["hom(e)(o)-", "same, similar", "Gk", "homeostasis"],
  ["humer(o)-", "humerus, shoulder", "L", "humeral head"],
  ["hydr(o)-", "water", "Gk", "hydrocephalus"],
  ["hyper-", "above, excessive", "Gk", "hypertension"],
  ["hyp(o)-", "below, deficient", "Gk", "hypoglycaemia, hypodermic"],
  ["hyster(o)-", "uterus", "Gk", "hysterectomy"],

  // I
  ["-ia, -iasis", "condition", "L/Gk", "anaemia, cholelithiasis"],
  ["iatr(o)-, -iatry", "physician, medicine", "Gk", "psychiatry, iatrogenic"],
  ["-ic", "pertaining to", "Gk", "hepatic, gastric"],
  ["idio-", "one's own, self", "Gk", "idiopathic"],
  ["ile(o)-", "ileum", "Gk", "ileocaecal valve"],
  ["ili(o)-", "ilium, flank", "L", "iliac crest"],
  ["infra-", "below, beneath", "L", "infraspinatus"],
  ["inter-", "between", "L", "intercostal, interosseous"],
  ["intra-", "within", "L", "intramuscular"],
  ["ipsi-", "same", "L", "ipsilateral"],
  ["irid(o)-", "iris, rainbow", "Gk", "iridectomy"],
  ["isch-", "restriction", "Gk", "ischaemia"],
  ["ischi(o)-", "ischium, hip joint", "Gk", "ischial tuberosity"],
  ["iso-", "equal", "Gk", "isotonic"],
  ["-itis", "inflammation", "Gk", "tonsillitis, arthritis"],
  ["-ium", "structure, tissue", "L", "pericardium, myocardium"],

  // J–K
  ["juxta-", "next to", "L", "juxtaglomerular"],
  ["kal-", "potassium", "L", "hyperkalaemia"],
  ["kary(o)-", "nucleus, nut", "Gk", "karyotype, eukaryote"],
  ["kerat(o)-", "cornea, horny tissue", "Gk", "keratin, keratitis"],
  ["kin(e)-, kinesi-", "movement", "Gk", "kinesthesia, akinesia"],
  ["koil-", "hollow", "Gk", "koilocyte"],
  ["kyph-", "humped, bent forward", "Gk", "kyphosis"],

  // L
  ["labi-", "lip", "L", "labial"],
  ["lacrim-", "tear", "L", "lacrimal gland"],
  ["lact(o)-", "milk", "L", "lactation, lactose"],
  ["lapar(o)-", "abdominal wall, flank", "Gk", "laparoscopy"],
  ["laryng(o)-", "larynx, voice box", "Gk", "laryngitis"],
  ["later(o)-", "side", "L", "lateral, bilateral"],
  ["lei(o)-", "smooth", "Gk", "leiomyoma"],
  ["-lepsy", "seizure, attack", "Gk", "epilepsy, narcolepsy"],
  ["lept(o)-", "thin, slender", "Gk", "leptomeninges"],
  ["leuk(o)-, leuc(o)-", "white", "Gk", "leukocyte, leukaemia"],
  ["lingu(o)-", "tongue", "L", "sublingual"],
  ["lip(o)-", "fat", "Gk", "liposuction, lipolysis"],
  ["lith(o)-", "stone", "Gk", "lithotripsy"],
  ["-logy, -logist", "study of, specialist in", "Gk", "cardiology"],
  ["lumb(o)-", "lower back, loin", "L", "lumbar puncture"],
  ["lymph(o)-", "lymph, clear water", "L", "lymphoedema"],
  ["-lysis, lys(o)-", "breakdown, loosening", "Gk", "haemolysis, lysosome"],

  // M
  ["macr(o)-", "large, long", "Gk", "macrophage"],
  ["-malacia", "softening", "Gk", "osteomalacia"],
  ["mamm(o)-", "breast", "L", "mammogram"],
  ["mandibul-", "lower jaw", "L", "mandibular nerve"],
  ["manu-", "hand", "L", "manubrium"],
  ["mast(o)-", "breast", "Gk", "mastectomy, mastitis"],
  ["maxill-", "upper jaw", "L", "maxillary sinus"],
  ["meg(a)-, -megaly", "large, enlargement", "Gk", "splenomegaly"],
  ["melan(o)-", "black, dark", "Gk", "melanoma, melanin"],
  ["mening(o)-", "membrane, meninges", "Gk", "meningitis"],
  ["men(o)-", "month, menses", "Gk", "menorrhagia, menopause"],
  ["mer(o)-", "part", "Gk", "merocrine"],
  ["mes(o)-", "middle", "Gk", "mesoderm, mesentery"],
  ["met(a)-", "beyond, after, change", "Gk", "metacarpal, metastasis"],
  ["-meter, -metry", "measure", "Gk", "spirometry"],
  ["metr(o)-", "uterus", "Gk", "endometrium, metrorrhagia"],
  ["micr(o)-", "small", "Gk", "microscope"],
  ["mon(o)-", "one, single", "Gk", "mononucleosis"],
  ["morph(o)-", "form, shape", "Gk", "morphology"],
  ["muscul(o)-", "muscle", "L", "musculoskeletal"],
  ["my(o)-", "muscle", "Gk", "myocardium, myopathy"],
  ["myc(o)-", "fungus", "Gk", "onychomycosis"],
  ["myel(o)-", "marrow, spinal cord", "Gk", "myelin, osteomyelitis"],
  ["myl(o)-", "molar, mill", "Gk", "mylohyoid"],
  ["myring(o)-", "eardrum", "L", "myringotomy"],
  ["myx(o)-", "mucus", "Gk", "myxoma"],

  // N
  ["nas(o)-", "nose", "L", "nasogastric"],
  ["nat-", "birth", "L", "neonatal"],
  ["necr(o)-", "death", "Gk", "necrosis"],
  ["neo-", "new", "Gk", "neoplasm"],
  ["nephr(o)-", "kidney", "Gk", "nephron, nephrectomy"],
  ["neur(o)-", "nerve", "Gk", "neurone, neuropathy"],
  ["noci-", "pain, injury", "L", "nociceptor"],

  // O
  ["ocul(o)-", "eye", "L", "oculomotor"],
  ["odont(o)-", "tooth", "Gk", "orthodontist"],
  ["-oid", "resembling", "Gk", "deltoid, sigmoid"],
  ["-ole, -ule", "small", "L", "arteriole, venule"],
  ["olig(o)-", "few, scanty", "Gk", "oliguria"],
  ["om(o)-", "shoulder", "Gk", "omohyoid"],
  ["-oma", "tumour, mass", "Gk", "carcinoma, haematoma"],
  ["omphal(o)-", "navel", "Gk", "omphalocele"],
  ["onco-", "tumour, bulk", "Gk", "oncology"],
  ["onych(o)-", "nail", "Gk", "onychomycosis"],
  ["oo-", "egg, ovum", "Gk", "oocyte, oogenesis"],
  ["oophor(o)-", "ovary", "Gk", "oophorectomy"],
  ["ophthalm(o)-", "eye", "Gk", "ophthalmology"],
  ["-opsy", "examination, viewing", "Gk", "biopsy, autopsy"],
  ["or(o)-", "mouth", "L", "oropharynx, orbicularis oris"],
  ["orchi(d)(o)-", "testis", "Gk", "orchiectomy"],
  ["orth(o)-", "straight, correct", "Gk", "orthopaedic"],
  ["-osis", "abnormal condition, process", "Gk", "osteoporosis, fibrosis"],
  ["oss-, oste(o)-", "bone", "L/Gk", "osteocyte, ossification"],
  ["ot(o)-", "ear", "Gk", "otitis, otoscope"],
  ["-ous", "pertaining to", "L", "cancellous, cavernous"],
  ["ovari(o)-", "ovary", "L", "ovarian"],
  ["ov(o)-, ov(i)-", "egg", "L", "ovulation"],
  ["ox(y)-", "sharp, acid; oxygen", "Gk", "hypoxia, oxytocin"],

  // P
  ["pachy-", "thick", "Gk", "pachymeningitis"],
  ["palpebr-", "eyelid", "L", "palpebral fissure"],
  ["pan-", "all, every", "Gk", "pancytopenia"],
  ["papill-", "nipple, small projection", "L", "papilloedema"],
  ["para-", "beside, near, abnormal", "Gk", "parathyroid, paraesthesia"],
  ["-paresis", "slight paralysis", "Gk", "hemiparesis"],
  ["path(o)-, -pathy", "disease, suffering", "Gk", "pathology, neuropathy"],
  ["pector-", "chest", "L", "pectoralis major"],
  ["ped-, -pes", "foot", "L", "pedal, talipes"],
  ["paed-, ped-", "child", "Gk", "paediatrics"],
  ["pelv(i)-", "pelvis, basin", "L", "pelvic floor"],
  ["-penia", "deficiency", "Gk", "thrombocytopenia"],
  ["-pepsia", "digestion", "Gk", "dyspepsia"],
  ["per-", "through", "L", "percutaneous"],
  ["peri-", "around", "Gk", "pericardium, periosteum"],
  ["-pexy", "surgical fixation", "Gk", "nephropexy"],
  ["phac(o)-, phak(o)-", "lens", "Gk", "phacoemulsification"],
  ["-phage, -phagia", "eating, swallowing", "Gk", "macrophage, dysphagia"],
  ["phall-", "penis", "Gk", "aphallia"],
  ["pharmac(o)-", "drug", "Gk", "pharmacology"],
  ["pharyng(o)-", "pharynx, throat", "Gk", "pharyngitis"],
  ["-phil(ia)", "attraction for", "Gk", "haemophilia, eosinophil"],
  ["phleb(o)-", "vein", "Gk", "phlebotomy"],
  ["-phobia", "fear, aversion", "Gk", "photophobia"],
  ["phon(o)-", "sound, voice", "Gk", "phonation"],
  ["phot(o)-", "light", "Gk", "photophobia"],
  ["phren(o)-", "diaphragm; also mind", "Gk", "phrenic nerve"],
  ["-phyte, phyto-", "growth, plant", "Gk", "osteophyte"],
  ["piri-", "pear-shaped", "L", "piriformis"],
  ["-plasia", "formation, development", "Gk", "hyperplasia, achondroplasia"],
  ["-plasty", "surgical repair", "Gk", "rhinoplasty"],
  ["-plegia", "paralysis", "Gk", "paraplegia"],
  ["pleur(o)-", "pleura, rib, side", "Gk", "pleurisy"],
  ["-pnea, -pnoea", "breathing", "Gk", "apnoea, dyspnoea"],
  ["pneum(at)(o)-", "air, lung, breath", "Gk", "pneumothorax"],
  ["pneumon-", "lung", "Gk", "pneumonia"],
  ["pod-, -pus", "foot", "Gk", "podiatry"],
  ["-poiesis", "production", "Gk", "haematopoiesis"],
  ["polio-", "grey", "Gk", "poliomyelitis"],
  ["poly-", "many", "Gk", "polydactyly, polyuria"],
  ["post-", "after, behind", "L", "postpartum, posterior"],
  ["pre-, pro-", "before, in front of", "L/Gk", "prenatal, prodrome"],
  ["presby-", "old age", "Gk", "presbyopia"],
  ["proct(o)-", "anus, rectum", "Gk", "proctology"],
  ["prosop(o)-", "face", "Gk", "prosopagnosia"],
  ["pseud(o)-", "false", "Gk", "pseudohypertrophy"],
  ["psych(o)-", "mind, soul", "Gk", "psychiatry"],
  ["pter(yg)(o)-", "wing", "Gk", "pterygoid"],
  ["-ptosis", "drooping, falling", "Gk", "nephroptosis, apoptosis"],
  ["-ptysis", "spitting", "Gk", "haemoptysis"],
  ["pulmon-", "lung", "L", "pulmonary artery"],
  ["py(o)-", "pus", "Gk", "pyogenic, empyema"],
  ["pyel(o)-", "renal pelvis", "Gk", "pyelonephritis"],
  ["pylor-", "gatekeeper", "Gk", "pyloric sphincter"],
  ["pyr(o)-", "fever, fire", "Gk", "antipyretic"],

  // Q–R
  ["quadr(i)-", "four", "L", "quadriceps"],
  ["rachi(o)-", "spine", "Gk", "rachischisis"],
  ["radi(o)-", "ray, radiation; radius", "L", "radiograph, radial"],
  ["radic-", "root", "L", "radiculopathy"],
  ["re-", "again, back", "L", "relapse"],
  ["rect-", "rectum; straight", "L", "rectus abdominis"],
  ["ren(o)-", "kidney", "L", "renal artery"],
  ["reticul(o)-", "net", "L", "reticulocyte"],
  ["retro-", "backward, behind", "L", "retroperitoneal"],
  ["rhabd(o)-", "rod-shaped, striated", "Gk", "rhabdomyolysis"],
  ["rhin(o)-", "nose", "Gk", "rhinoplasty, rhinitis"],
  ["-rrhagia", "bursting forth, heavy flow", "Gk", "menorrhagia"],
  ["-rrhaphy", "surgical suturing", "Gk", "herniorrhaphy"],
  ["-rrhoea, -rrhea", "flow, discharge", "Gk", "diarrhoea"],
  ["-rrhexis", "rupture", "Gk", "karyorrhexis"],
  ["rubr(o)-", "red", "L", "rubrospinal tract"],

  // S
  ["salping(o)-", "tube, trumpet", "Gk", "salpingectomy"],
  ["sangui-", "blood", "L", "sanguineous"],
  ["sarc(o)-", "flesh, muscle", "Gk", "sarcoma, sarcomere"],
  ["scapul(o)-", "shoulder blade", "L", "scapulothoracic"],
  ["schist(o)-, schiz(o)-", "split, cleft", "Gk", "schistocyte"],
  ["scler(o)-, -sclerosis", "hard, hardening", "Gk", "scleroderma"],
  ["scoli(o)-", "twisted, curved", "Gk", "scoliosis"],
  ["-scope, -scopy", "instrument for viewing, examination", "Gk", "endoscopy"],
  ["semi-", "half, partly", "L", "semilunar"],
  ["sial(o)-", "saliva", "Gk", "sialolithiasis"],
  ["sigmoid-", "S-shaped", "Gk", "sigmoid colon"],
  ["sinistr(o)-", "left", "L", "sinistrocardia"],
  ["sinus-", "hollow, cavity", "L", "sinusitis"],
  ["somat(o)-", "body", "Gk", "somatic, somatostatin"],
  ["somn(o)-", "sleep", "L", "insomnia"],
  ["spasm(o)-", "involuntary contraction", "Gk", "bronchospasm"],
  ["sperm(at)(o)-", "seed, semen", "Gk", "spermatogenesis"],
  ["splanchn(o)-", "viscera", "Gk", "splanchnic nerve"],
  ["splen(o)-", "spleen", "Gk", "splenectomy"],
  ["spondyl(o)-", "vertebra", "Gk", "spondylolisthesis"],
  ["squam(o)-", "scaly", "L", "squamous cell"],
  ["-stasis", "stopping, controlling", "Gk", "haemostasis"],
  ["-staxis", "dripping", "Gk", "epistaxis"],
  ["sten(o)-, -stenosis", "narrow, narrowing", "Gk", "aortic stenosis"],
  ["steth(o)-", "chest", "Gk", "stethoscope"],
  ["stom(at)(o)-, -stomy", "mouth, opening", "Gk", "colostomy, stomatitis"],
  ["sub-", "under, below", "L", "subclavian, sublingual"],
  ["super-, supra-", "above, excessive", "L", "supraspinatus"],
  ["sy(l)(m)(n)-", "together, with", "Gk", "symphysis, syndrome"],

  // T
  ["tachy-", "fast", "Gk", "tachycardia, tachypnoea"],
  ["tars(o)-", "ankle; edge of eyelid", "Gk", "metatarsal"],
  ["-tension", "pressure", "L", "hypertension"],
  ["terato-", "monster, malformation", "Gk", "teratogen"],
  ["thec-", "case, sheath", "Gk", "intrathecal"],
  ["thel-", "nipple", "Gk", "thelarche"],
  ["therm(o)-", "heat", "Gk", "hypothermia"],
  ["thorac(o)-", "chest", "Gk", "thoracotomy"],
  ["thromb(o)-", "clot", "Gk", "thrombosis"],
  ["thym-", "emotion; thymus", "Gk", "dysthymia"],
  ["thyr(o)-", "shield (thyroid)", "Gk", "thyroidectomy"],
  ["-tome, -tomy", "cutting instrument, incision", "Gk", "osteotome, laparotomy"],
  ["ton(o)-", "tone, tension", "Gk", "isotonic, hypotonia"],
  ["top(o)-", "place", "Gk", "topical, ectopic"],
  ["tort(i)-", "twisted", "L", "torticollis"],
  ["tox(ic)(o)-", "poison", "Gk", "toxaemia"],
  ["trache(o)-", "trachea, windpipe", "Gk", "tracheostomy"],
  ["trachel(o)-", "neck", "Gk", "tracheloplasty"],
  ["trans-", "across, through", "L", "transverse, transfusion"],
  ["tri-", "three", "L", "triceps, trisomy"],
  ["trich(o)-", "hair", "Gk", "trichotillomania"],
  ["-tripsy", "crushing", "Gk", "lithotripsy"],
  ["-trophy, troph(o)-", "nourishment, growth", "Gk", "hypertrophy, atrophy"],
  ["-tropic", "turning toward, affecting", "Gk", "inotropic, gonadotropic"],
  ["tympan(o)-", "eardrum, drum", "Gk", "tympanic membrane"],

  // U–Z
  ["ultra-", "beyond, excessive", "L", "ultrasound"],
  ["umbilic-", "navel", "L", "umbilical"],
  ["ungui-", "nail, claw", "L", "unguiform"],
  ["uni-", "one", "L", "unilateral"],
  ["ur(o)-, -uria", "urine, urinary tract", "Gk", "polyuria, urology"],
  ["ureter(o)-", "ureter", "Gk", "ureteroscopy"],
  ["urethr(o)-", "urethra", "Gk", "urethritis"],
  ["uter(o)-", "uterus, womb", "L", "uterine"],
  ["vagin-", "sheath, vagina", "L", "invaginate"],
  ["varic(o)-", "swollen or twisted vein", "L", "varicose"],
  ["vas(o)-", "vessel, duct", "L", "vasoconstriction, vas deferens"],
  ["vascul(o)-", "vessel", "L", "cardiovascular"],
  ["ven(o)-", "vein", "L", "venous, venule"],
  ["ventr(o)-", "belly, front", "L", "ventral"],
  ["ventricul(o)-", "ventricle, little belly", "L", "ventriculography"],
  ["-version", "turning", "L", "anteversion, retroversion"],
  ["vesic(o)-", "bladder, blister", "L", "vesicoureteric"],
  ["viscer(o)-", "internal organ", "L", "visceral pleura"],
  ["xanth(o)-", "yellow", "Gk", "xanthelasma"],
  ["xen(o)-", "foreign", "Gk", "xenograft"],
  ["xer(o)-", "dry", "Gk", "xerostomia"],
  ["xiph(o)-", "sword", "Gk", "xiphoid process"],
  ["zyg(o)-", "yoke, union, pair", "Gk", "zygote, zygomatic"],

  // --- further roots, prefixes and suffixes ---
  ["acanth(o)-", "thorn, spine", "Gk", "acanthocyte"],
  ["arch(i)-", "first, primitive", "Gk", "archinephron"],
  ["arsen(o)-", "male, masculine", "Gk", "arsenoblast"],
  ["-ation", "process", "L", "medication, ossification"],
  ["aux(o)-", "increase, growth", "Gk", "auxocardia"],
  ["azo(to)-", "nitrogenous compound", "Gk", "azotaemia"],
  ["cerat(o)-", "horn", "Gk", "ceratoid"],
  ["cis-", "on this side", "L", "cisterna"],
  ["clostr(o)-", "spindle", "Gk", "Clostridium"],
  ["cycl(o)-", "circle, cycle; ciliary body", "Gk", "cyclitis, cycloplegia"],
  ["cyph(o)-", "bent, hunched", "Gk", "cyphosis"],
  ["dromo-, -drome", "running, conduction", "Gk", "dromotropic, syndrome"],
  ["esthesio-, aesthesio-", "sensation", "Gk", "anaesthesia, paraesthesia"],
  ["fossa", "trench, shallow depression", "L", "fossa ovalis"],
  ["halluc-", "to wander in mind", "L", "hallucination"],
  ["-icle, -ula, -ule", "small", "L", "ovarian follicle, nodule, venule"],
  ["-ics", "organised knowledge, practice", "Gk", "obstetrics, orthotics"],
  ["-ism", "condition, state", "Gk", "hypothyroidism, dwarfism"],
  ["-ismus", "spasm, contraction", "Gk", "hemiballismus"],
  ["-ist", "one who specialises in", "Gk", "pathologist"],
  ["-ite", "of the nature of", "Gk", "dendrite"],
  ["-ity", "pertaining to, state of", "L", "immunity"],
  ["log(o)-", "speech, word", "Gk", "logopenic aphasia"],
  ["melos", "limb, extremity", "Gk", "erythromelalgia"],
  ["milli-", "thousandth", "L", "millilitre"],
  ["myri-", "ten thousand, countless", "Gk", "myriad"],
  ["norm(o)-", "normal", "L", "normocapnia, normocytic"],
  ["-one", "hormone, ketone", "Gk", "testosterone"],
  ["op-, opt-", "vision, sight", "Gk", "optic nerve, myopia"],
  ["optic(o)-", "of the eye's optics", "Gk", "opticochemical"],
  ["-or", "one who, that which", "L", "flexor, doctor"],
  ["osse-, ossi-", "bone, bony", "L", "osseous tissue, ossification"],
  ["oxo-", "addition of oxygen", "Gk", "oxidative"],
  ["papul(o)-", "pimple, small swelling", "L", "papulation"],
  ["peo-", "penis", "Gk", "peotomy"],
  ["phagist-", "one who feeds on", "Gk", "geophagist"],
  ["phos-", "light (archaic)", "Gk", "phosphene"],
  ["pleio-, pleo-", "more, excessive", "Gk", "pleiotropy"],
  ["-plexy", "stroke, seizure", "Gk", "cataplexy, apoplexy"],
  ["por(o)-", "pore, passage", "Gk", "osteoporosis"],
  ["porphyr(o)-", "purple", "Gk", "porphyria"],
  ["prim-", "first, most important", "L", "primary, primipara"],
  ["prot(o)-", "first", "Gk", "protoplasm"],
  ["psor-", "itching", "Gk", "psoriasis"],
  ["-rupt", "break, burst", "L", "erupt, interrupt"],
  ["sapro-", "rotten, decaying", "Gk", "saprophyte"],
  ["sito-", "food, grain", "Gk", "sitophobia"],
  ["-stalsis", "contraction", "Gk", "peristalsis"],
  ["sthen(o)-, -sthenia", "strength", "Gk", "asthenia, myasthenia"],
  ["thely-", "female, feminine", "Gk", "thelygenous"],
  ["therap-", "treatment", "Gk", "therapeutic, hydrotherapy"],
  ["-tony", "tension, tone", "Gk", "hypotonia"],
  ["uric-", "uric acid", "Gk", "uricaemia"],
  ["urin(o)-", "urine", "L", "uriniferous"],
  ["-y", "condition or process of", "Gk", "surgery, atrophy"],
  ["zo(o)-", "animal", "Gk", "zoonosis"],
  ["zym(o)-, -zyme", "fermentation, enzyme", "Gk", "lysozyme, enzyme"],

  // --- Latin counterparts of the Greek body roots ---
  ["abdomin(o)-", "abdomen", "L", "abdominoplasty"],
  ["aort(o)-", "aorta", "Gk", "aortic arch"],
  ["allic-", "great toe", "L", "hallux"],
  ["corpor-", "body", "L", "corpus callosum"],
  ["medull(o)-", "marrow, inner part", "L", "adrenal medulla"],
  ["fell-", "gallbladder, bile", "L", "fellic"],
  ["jecor-", "liver", "L", "jecoral"],
  ["ment-", "mind; also chin", "L", "mental, mentalis"],
  ["pudend-", "external genitals", "L", "pudendal nerve"],
  ["pollic-", "thumb", "L", "pollicis"],
  ["cuticul-", "skin", "L", "cuticle"],
  ["nerv-", "nerve", "L", "nervous system"],
  ["ren-", "kidney", "L", "renal artery"],
  ["vulv(o)-", "vulva", "L", "vulvodynia"],

  // --- colour, in both languages ---
  ["nigr-", "black", "L", "substantia nigra"],
  ["rub-, rubr-", "red", "L", "rubrospinal, bilirubin"],
  ["flav-", "yellow", "L", "flavoprotein"],
  ["vir(id)-", "green", "L", "viridans streptococci"],
  ["purpur-", "purple", "L", "purpura"],
  ["cirrh(o)-", "orange-yellow", "Gk", "cirrhosis"],
  ["rhod(o)-", "rose-red", "Gk", "rhodopsin"],

  // --- size, shape and quality ---
  ["cac(o)-", "bad, ill", "Gk", "cacosmia"],
  ["mal-, male-", "bad, abnormal", "L", "malignant, malformation"],
  ["prav-", "crooked, depraved", "L", "pravity"],
  ["poikil(o)-", "varied, irregular", "Gk", "poikilocytosis"],
  ["coel(o)-", "hollow", "Gk", "coelom"],
  ["cav(i)-", "hollow", "L", "cavity, vena cava"],
  ["bar(o)-", "weight, pressure", "Gk", "baroreceptor"],
  ["grav(i)-", "heavy", "L", "gravid"],
  ["eury-", "wide, broad", "Gk", "eurycephalic"],
  ["lat(i)-", "wide, broad", "L", "latissimus dorsi"],
  ["platy-", "flat, broad", "Gk", "platysma"],
  ["plan(i)-", "flat", "L", "planar"],
  ["megist-", "largest", "Gk", "megistotherm"],
  ["magn(i)-", "large, great", "L", "magnus, foramen magnum"],
  ["maxim-", "largest", "L", "gluteus maximus"],
  ["minim-", "smallest", "L", "digiti minimi"],
  ["parv(i)-", "small", "L", "parvovirus"],
  ["malac(o)-, -malacia", "soft, softening", "Gk", "osteomalacia"],
  ["moll(i)-", "soft", "L", "molluscum"],
  ["dur(i)-", "hard, tough", "L", "dura mater, induration"],
  ["crass(i)-", "thick", "L", "crassitude"],
  ["angust(i)-", "narrow", "L", "angustation"],
  ["brev(i)-", "short", "L", "peroneus brevis"],
  ["long(i)-", "long", "L", "longus colli"],
  ["nov(i)-, ne(o)-", "new", "L/Gk", "neonate, novel"],
  ["paleo-, palaeo-", "old, ancient", "Gk", "palaeocortex"],
  ["veter-", "old", "L", "inveterate"],
  ["ac-, acr-", "sharp, pointed", "L", "acute, acumen"],
  ["frig(i)-", "cold", "L", "frigid"],
  ["celer-", "fast", "L", "acceleration"],
  ["tard(i)-", "slow", "L", "tardive dyskinesia"],
  ["mort-", "death", "L", "mortality, rigor mortis"],
  ["equ(i)-", "equal", "L", "equilibrium"],
  ["fals(i)-", "false", "L", "falsification"],
  ["ben(e)-, bon(i)-", "good, well", "L", "benign"],
  ["vari-", "varied", "L", "variation, variola"],

  // --- position and quantity ---
  ["levo-, laev(o)-", "left", "L/Gk", "levocardia"],
  ["dexi(o)-, dextr(o)-", "right", "L/Gk", "dextrocardia"],
  ["medi-", "middle", "L", "medial, mediastinum"],
  ["dupli-, diplo-", "double", "L/Gk", "duplication, diploid"],
  ["bis-", "twice", "L", "bisect"],
  ["multi-", "many", "L", "multipara, multifidus"],
  ["pauci-", "few", "L", "pauci-immune"],
  ["quadr(i)-, tetra-", "four", "L/Gk", "quadriceps, tetralogy"],
  ["mon(o)-, uni-", "one", "L/Gk", "monocyte, unilateral"],
  ["hetero-", "other, different", "Gk", "heterogeneous"],
  ["hom(o)-", "same", "Gk", "homozygous"],
];

export const ANATOMY_REFERENCE: ReferenceEntry[] = ROWS.map(
  ([form, meaning, origin, example]) => ({ form, meaning, origin, example })
);

/** The bare letters of a form: "cyt(o)-, -cyte" → ["cyt", "cyto", "cyte"]. */
function variantsOf(form: string): string[] {
  const out = new Set<string>();
  for (const piece of form.split(",")) {
    const trimmed = piece.trim().replace(/^-|-$/g, "");
    // Optional segments in parentheses give two readings: with and without.
    out.add(trimmed.replace(/[()]/g, "").toLowerCase());
    out.add(trimmed.replace(/\([^)]*\)/g, "").toLowerCase());
  }
  return [...out].filter(Boolean);
}

const INDEX = ANATOMY_REFERENCE.map((entry) => ({
  entry,
  variants: variantsOf(entry.form),
  haystack: `${entry.meaning} ${entry.example ?? ""}`.toLowerCase(),
}));

/**
 * Looks up word parts. Matches on the form first — typing "cyto" should lead
 * with cyt(o)- rather than every entry that happens to mention cells — then
 * falls back to meanings and examples so "kidney" finds nephr- and ren-.
 */
export function searchReference(query: string, limit = 40): ReferenceEntry[] {
  const q = query.trim().toLowerCase().replace(/^-|-$/g, "");
  if (!q) return [];
  const exact: ReferenceEntry[] = [];
  const prefix: ReferenceEntry[] = [];
  const inside: ReferenceEntry[] = [];
  const byMeaning: ReferenceEntry[] = [];

  for (const { entry, variants, haystack } of INDEX) {
    if (variants.some((v) => v === q)) exact.push(entry);
    else if (variants.some((v) => v.startsWith(q))) prefix.push(entry);
    else if (variants.some((v) => q.startsWith(v) && v.length >= 3)) inside.push(entry);
    else if (haystack.includes(q)) byMeaning.push(entry);
  }
  return [...exact, ...prefix, ...inside, ...byMeaning].slice(0, limit);
}
